"""One turn: read the repository, do exactly one thing, record it, commit, exit.

There is no workflow object here and there is deliberately nothing for one to attach to (S173). The
phase is read from the backlog's state, never declared, so ordering is a consequence rather than a
list someone maintains.

The split this module exists to enforce (architecture.md §1): the agent proposes **one** typed event
and the code disposes of it. Appending *is* the check — the candidate log is folded before it
replaces the real one — so nothing here holds a second copy of which transitions are legal, and a
rejected proposal leaves the item byte-for-byte as it was. That last property is what makes a failed
turn safe to retry.

Identifiers are generated without reading anything (S186). A scheme that reads the current maximum is
a lock in disguise: two planning turns both read the same highest id and write the same new one.
"""

from __future__ import annotations

import json
import os
import secrets
import subprocess
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any, Protocol
from uuid import uuid4

from yosefactory.executor.outcome import RunOutcome, RunResult
from yosefactory.protocol import backlog, question
from yosefactory.protocol.eventlog import Declaration, FoldedLog, LogError
from yosefactory.protocol.eventlog import load as load_log
from yosefactory.protocol.turn import EnforcedBy, Outcome, TurnRecord
from yosefactory.runtime import runs, verify
from yosefactory.runtime.config import Guardrails
from yosefactory.runtime.supervise import single_flight, tree_is_dirty

ITEMS = Path("backlog/items")
QUESTIONS = Path("questions")
RUNS = Path("ledger") / runs.STREAM_DIRNAME
LOCK = Path(".git") / "yosefactory-turn.lock"

# The event log's own fields. An agent that supplies one is refused rather than overridden: dedup and
# replay order both key on them, and they may not come from the component S098 measured as unreliable.
RESERVED = ("event_id", "ts", "actor")

_STAMP = "%Y%m%dT%H%M%SZ"

DEFAULT_PLANNING_FRAME: Mapping[str, Any] = {
    "goal": "Emit the next work item, or several, for this loop.",
    "method": "Read the repository. Propose `created` events; do not act on them.",
    "assumptions": "Nothing is in flight; a planned item is inert until a later turn claims it.",
}


class TurnError(RuntimeError):
    """The turn refused to proceed. Never raised for an agent's bad proposal — that is an outcome."""


class Executor(Protocol):
    """The seam. `frame` carries D019's three fields plus `proposal_path` and `skill`."""

    def __call__(
        self,
        frame: Mapping[str, Any],
        workspace: Path,
        limits: Guardrails,
        *,
        run_id: str,
        runs_dir: Path,
    ) -> RunResult: ...


@dataclass(frozen=True, slots=True)
class Refusal:
    """Why a proposal was not written. The item is unchanged; the turn records `failed`."""

    detail: str


def utc_now(moment: datetime | None = None) -> str:
    return (moment or datetime.now(UTC)).isoformat()


def new_item_id(moment: datetime | None = None) -> str:
    """`itm-<stamp>-<8 hex>`, matching the question format. Generated blind — nothing is read."""
    return f"itm-{(moment or datetime.now(UTC)).strftime(_STAMP)}-{secrets.token_hex(4)}"


def new_run_id(moment: datetime | None = None) -> str:
    return f"turn-{(moment or datetime.now(UTC)).strftime(_STAMP)}-{secrets.token_hex(4)}"


def append(path: Path, declaration: Declaration, payload: Mapping[str, Any], *, actor: str) -> FoldedLog:
    """Append one event, or leave the log untouched and raise.

    The candidate is folded in a temporary file and renamed over the log only once the fold accepts
    it, so an illegal transition, an unknown event or a missing field costs the log nothing.
    """
    for field in RESERVED:
        if field in payload:
            raise TurnError(f"{field!r} is generated by the turn; an event may not carry its own")
    if not payload.get("event"):
        raise TurnError("an event must name itself")

    record = {"event_id": uuid4().hex, "ts": utc_now(), "actor": actor, **payload}
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    candidate = path.with_name(path.name + ".candidate")
    candidate.parent.mkdir(parents=True, exist_ok=True)
    candidate.write_text(existing + json.dumps(record, sort_keys=True) + "\n", encoding="utf-8")
    try:
        folded = load_log(candidate, declaration, log_id=path.stem)
    except LogError:
        candidate.unlink(missing_ok=True)
        raise
    candidate.replace(path)
    return folded


def items(repo: Path) -> list[FoldedLog]:
    return [backlog.load(path) for path in sorted((repo / ITEMS).glob("*.jsonl"))]


def eligible(item: FoldedLog) -> bool:
    """`ready` and nothing else. Waking a snoozed item is a sweeper's job and there is no sweeper."""
    return item.state == "ready"


def should_plan(backlog_items: Sequence[FoldedLog]) -> bool:
    """Plan only when nothing is in flight.

    Work that exists but is blocked or snoozed is not an argument for making more of it — that is how
    a backlog fills with slop while the real item waits on an answer. `nothing-ready` is the honest
    record of that state, and it is the one architecture.md §8 needs in order to see a green stall.
    """
    return not any(not item.terminal for item in backlog_items)


def pick(candidates: Sequence[FoldedLog]) -> FoldedLog | None:
    """Highest priority, then lowest id. Deterministic, so two turns pick the same item and the
    claim — not the ordering — is what resolves the collision."""
    ranked = sorted(candidates, key=lambda item: (-int(backlog.priority(item) or 0), item.id))
    return ranked[0] if ranked else None


def apply_answers(repo: Path, *, actor: str) -> list[str]:
    """Unblock every item whose question has closed. Returns the item ids that moved.

    The target state is read from the block's own `awaiting.return_to` by the fold, never recomputed
    here — it was decided when the block was written.

    No steering inbox is read: no such format exists in this repository (design-e2e.md §1 describes
    one and nothing implements it). Recorded as a gap rather than invented.
    """
    moved: list[str] = []
    for path in sorted((repo / QUESTIONS).glob("*.jsonl")):
        asked = question.load(path)
        closed = question.outcome(asked)
        if closed is None:
            continue
        item_id = str(question.asked(asked)["item"])
        item_path = repo / ITEMS / f"{item_id}.jsonl"
        if not item_path.exists() or backlog.load(item_path).state != "blocked":
            continue
        append(
            item_path,
            backlog.ITEM,
            {"event": "unblocked", "resolution": {"qid": path.stem, "by": str(closed["event"])}},
            actor=actor,
        )
        moved.append(item_id)
    return moved


def read_proposal(path: Path, *, planning: bool) -> list[dict[str, Any]] | Refusal:
    """One JSON object, or — for a planning turn only — a list of them.

    A missing file is a refusal rather than an absence: an agent that wrote nothing did not decline,
    it failed, and the two must not read alike.
    """
    if not path.exists():
        return Refusal("the agent wrote no proposal")
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return Refusal(f"proposal is not valid JSON: {exc.msg}")

    events = payload if isinstance(payload, list) else [payload]
    if not events:
        return Refusal("proposal carries no event")
    if not planning and len(events) != 1:
        return Refusal(f"an acting turn proposes exactly one event; got {len(events)}")
    for event in events:
        if not isinstance(event, dict):
            return Refusal(f"an event must be a JSON object, got {type(event).__name__}")
        if not event.get("event"):
            return Refusal("an event must name itself")
        for field in RESERVED:
            if field in event:
                return Refusal(f"an event may not carry its own {field!r}")
    return events


def outcome_for(state: str) -> Outcome:
    """What the item's new state means for the turn. `done` is not the only way to advance —
    `falsified` advanced the knowledge, which is what this platform exists to accumulate."""
    if state == "blocked":
        return Outcome.BLOCKED
    if state in ("failed", "poison"):
        return Outcome.FAILED
    return Outcome.ADVANCED


def commit(repo: Path, paths: Sequence[Path], message: str) -> None:
    """Explicit pathspecs on every git call. The index is shared; `commit -- <paths>` ignores it."""
    present = [path for path in paths if path.exists()]
    if not present:
        return
    relative = [str(path.relative_to(repo)) for path in present]
    env = {**os.environ, "PREK_ALLOW_NO_CONFIG": "1"}
    _git(repo, ["add", "--", *relative], env)
    committed = _git(repo, ["commit", "-m", message, "--", *relative], env, check=False)
    if committed.returncode != 0:
        _git(repo, ["restore", "--staged", "--", *relative], env, check=False)
        tail = (committed.stdout or committed.stderr).strip().splitlines()[-1:] or ["no output"]
        raise TurnError(f"commit refused: {tail[0]}")


def _git(repo: Path, argv: list[str], env: dict[str, str], *, check: bool = True) -> subprocess.CompletedProcess[str]:
    completed = subprocess.run(  # noqa: S603
        ["git", *argv],  # noqa: S607
        cwd=repo,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    if check and completed.returncode != 0:
        raise TurnError(f"git {argv[0]} failed: {(completed.stderr or completed.stdout).strip()}")
    return completed


def take_turn(
    repo: Path,
    executor: Executor,
    *,
    limits: Guardrails,
    owner: str,
    skill: Path,
    planning_frame: Mapping[str, Any] = DEFAULT_PLANNING_FRAME,
    loop: str = "default",
    proposal_dir: Path | None = None,
    test_command: tuple[str, ...] = verify.DEFAULT_TEST_COMMAND,
    isolated: bool = True,
    cross_machine: bool = False,
    cas_push: bool = False,
    phase: str | None = None,
    now: datetime | None = None,
) -> TurnRecord:
    """Acquire, classify, do one item, record, commit, exit. Returns the record it wrote.

    `phase` exists only to be refused. The phase is a consequence of the backlog's state, and a caller
    that names it has a different design in mind (S173).
    """
    if phase is not None:
        raise TurnError("the phase is derived from item state and cannot be supplied")
    if cross_machine and not cas_push:
        raise TurnError(
            "cross-machine operation needs the compare-and-swap claim push, which is not enabled; "
            "a single-machine turn is protected by the lock and a multi-machine turn is not"
        )

    started = now or datetime.now(UTC)
    run_id = new_run_id(started)
    scratch = proposal_dir or Path(os.environ.get("TMPDIR", "/tmp"))  # noqa: S108
    # Outside the repository, so a killed run cannot leave the tree dirty and fail another worker's
    # commit — the tree-wide stash S184 records makes that everyone's problem, not just this turn's.
    proposal_path = scratch / f"{run_id}.proposal.json"

    with single_flight(repo / LOCK):
        apply_answers(repo, actor=owner)
        present = items(repo)
        target = pick([item for item in present if eligible(item)])

        if target is None and not should_plan(present):
            return _finish(
                repo,
                started,
                run_id,
                Outcome.NOTHING_READY,
                EnforcedBy.HARNESS,
                note="nothing eligible; no agent was started",
                paths=[],
                isolated=isolated,
            )

        if target is None:
            frame = {**planning_frame, "proposal_path": str(proposal_path), "skill": str(skill)}
            result = executor(frame, repo, limits, run_id=run_id, runs_dir=repo / RUNS)
            return _dispose(
                repo,
                started,
                run_id,
                result,
                item_path=None,
                proposal_path=proposal_path,
                owner=owner,
                loop=loop,
                isolated=isolated,
                test_command=test_command,
            )

        item_path = repo / ITEMS / f"{target.id}.jsonl"
        attempt = int((backlog.lease(target) or {}).get("attempt", 0)) + 1
        append(
            item_path,
            backlog.ITEM,
            {
                "event": "claimed",
                "owner": owner,
                "expires_at": (started + timedelta(seconds=limits.wall_clock_seconds)).isoformat(),
                "attempt": attempt,
            },
            actor=owner,
        )
        append(item_path, backlog.ITEM, {"event": "started"}, actor=owner)
        # Committed before the agent runs: a crash from here on is legible as claimed-and-abandoned
        # rather than never-started, which is the state architecture.md §4 found v1 had deleted.
        commit(repo, [item_path], f"claim({target.id}): attempt {attempt} by {owner}")

        frame = {**backlog.frame(backlog.load(item_path)), "proposal_path": str(proposal_path), "skill": str(skill)}
        result = executor(frame, repo, limits, run_id=run_id, runs_dir=repo / RUNS)
        return _dispose(
            repo,
            started,
            run_id,
            result,
            item_path=item_path,
            proposal_path=proposal_path,
            owner=owner,
            loop=loop,
            isolated=isolated,
            test_command=test_command,
        )


def _dispose(
    repo: Path,
    started: datetime,
    run_id: str,
    result: RunResult,
    *,
    item_path: Path | None,
    proposal_path: Path,
    owner: str,
    loop: str,
    isolated: bool,
    test_command: tuple[str, ...],
) -> TurnRecord:
    planning = item_path is None
    subject = "planning" if planning else item_path.stem
    touched = [] if item_path is None else [item_path]

    def failed(detail: str) -> TurnRecord:
        return _finish(
            repo,
            started,
            run_id,
            Outcome.FAILED,
            EnforcedBy.HARNESS,
            note=f"{subject}: {detail}",
            paths=touched,
            isolated=isolated,
        )

    if result.outcome is not RunOutcome.SUCCESS:
        return failed(f"executor reported {result.outcome.value} ({result.failure_kind or 'no kind'}): {result.detail}")

    proposed = read_proposal(proposal_path, planning=planning)
    if isinstance(proposed, Refusal):
        return failed(proposed.detail)

    if planning:
        written: list[Path] = []
        for event in proposed:
            path = repo / ITEMS / f"{new_item_id()}.jsonl"
            try:
                append(path, backlog.ITEM, {"loop": loop, **event}, actor=owner)
            except (LogError, TurnError) as exc:
                for done in written:
                    done.unlink(missing_ok=True)
                return failed(f"proposal refused: {exc}")
            written.append(path)
        return _finish(
            repo,
            started,
            run_id,
            Outcome.ADVANCED,
            EnforcedBy.AGENT,
            note=f"planned {len(written)} item(s): {', '.join(path.stem for path in written)}",
            paths=written,
            isolated=isolated,
        )

    assert item_path is not None  # noqa: S101 — narrowed by `planning`, which ty cannot see through
    event = proposed[0]
    if event["event"] == "done":
        claim = verify.Claim(run_id=run_id, terminal_verdict=result.outcome.value)
        gate = verify.may_write_done(repo, claim, test_command=test_command)
        if not gate.passed:
            return failed(gate.report())

    try:
        folded = append(item_path, backlog.ITEM, event, actor=owner)
    except (LogError, TurnError) as exc:
        return failed(f"proposal refused: {exc}")

    return _finish(
        repo,
        started,
        run_id,
        outcome_for(folded.state),
        EnforcedBy.AGENT,
        note=f"{subject}: {event['event']} -> {folded.state}",
        paths=[item_path],
        isolated=isolated,
    )


def _finish(
    repo: Path,
    started: datetime,
    run_id: str,
    outcome: Outcome,
    enforced_by: EnforcedBy,
    *,
    note: str,
    paths: Sequence[Path],
    isolated: bool,
) -> TurnRecord:
    runs_dir = repo / RUNS
    slug = runs.open_run(runs_dir, run_id, started)
    record = TurnRecord(
        run_id=run_id,
        started_at=started.isoformat(),
        ended_at=utc_now(),
        outcome=outcome,
        enforced_by=enforced_by,
        dirty=tree_is_dirty(repo, ignore=runs_dir),
        isolated=isolated,
        note=note,
    )
    written = runs.append(runs_dir, slug, record)
    commit(repo, [*paths, written, written.with_suffix(".start")], f"turn({run_id}): {outcome.value} — {note}")
    return record
