"""The board's own event shape, and the command syntax a human types to produce one.

architecture.md §7: "a priority change and an answer are both EVENTS: { event_id, ts, actor, type:
set_priority | answer | cancel, payload }". This module defines that record and the one thing that
turns free text in a comment box into it -- design.md D3: a leading slash-token, one command per
comment, because that is what "type something and send it" from a phone actually is.
"""

from __future__ import annotations

import re
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

TYPES = frozenset({"set_priority", "answer", "cancel", "create"})

_PRIORITY = re.compile(r"^/priority\s+(-?\d+)\s*$")
_ANSWER = re.compile(r"^/answer\s+(.+)$", re.DOTALL)
_CANCEL = re.compile(r"^/cancel\s+(.+)$", re.DOTALL)


@dataclass(frozen=True, slots=True)
class Event:
    """One board-side command, already typed. `event_id`/`ts`/`actor` are the board's own —
    never regenerated by `ingest()`, which is what makes re-ingestion idempotent (design.md D4)."""

    event_id: str
    ts: str
    actor: str
    type: str
    payload: Mapping[str, Any]

    def __post_init__(self) -> None:
        if self.type not in TYPES:
            raise ValueError(f"event type {self.type!r} is not one of {sorted(TYPES)}")


def parse_command(text: str) -> tuple[str, Mapping[str, Any]] | None:
    """A comment body -> (type, payload), or `None` if it is not a command at all.

    `None` is not a rejection -- a comment that does not open with `/` is Denis narrating, not
    addressing the board, and `list_events()` drops it before it ever becomes an `Event`
    (spec: "A comment that does not start with `/` is ignored").  A comment that *does* start
    with `/` but does not match a known shape (`/prioritize`, `/priority high`) is where
    rejection begins -- callers get that by trying `parse_command` and getting `None` back too,
    then reporting explicitly.  That collapse is deliberate: this function answers "is this any
    command I recognise", and a caller distinguishing "not a command" from "a bad command" would
    need the raw text anyway, which it already has.
    """
    stripped = text.strip()
    if not stripped.startswith("/"):
        return None
    if match := _PRIORITY.match(stripped):
        return "set_priority", {"priority": int(match.group(1))}
    if match := _ANSWER.match(stripped):
        return "answer", {"answer": match.group(1).strip()}
    if match := _CANCEL.match(stripped):
        return "cancel", {"reason": match.group(1).strip()}
    return None
