"""WorkAdapter Protocol + in-tree work impls."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from a2sdlc.domain.handover import FeedbackItem, HandoverComment
from a2sdlc.domain.models import StageName
from a2sdlc.domain.pipeline_event import PipelineEvent


class WorkAdapter(Protocol):
    """Platform-specific ticket/work-item operations."""

    def parse_event(self) -> PipelineEvent: ...
    def get_ticket(self, key: str) -> str: ...
    def get_labels(self, key: str) -> list[str]: ...
    def begin_comment(self, key: str) -> str: ...
    def update_progress(self, comment_id: str, body: str) -> None: ...
    def finalize_comment(self, comment_id: str, body: str) -> None: ...
    def set_stage_label(self, key: str, stage: StageName) -> None: ...
    def set_done_label(self, key: str) -> None: ...
    def set_blocked(self, key: str, reason: str) -> None: ...
    def format_branch(self, ticket_key: str) -> str: ...
    def collect_issue_feedback(
        self, key: str, since: datetime
    ) -> list[FeedbackItem]: ...
    def find_last_handover(self, key: str) -> HandoverComment | None: ...


from a2sdlc.adapters.work.local_file import LocalFileWorkAdapter  # noqa: E402
from a2sdlc.adapters.work.github import GitHubWorkAdapter  # noqa: E402

__all__ = ["WorkAdapter", "LocalFileWorkAdapter", "GitHubWorkAdapter"]
